package com.logmind.tasklog.core.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF000000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF333333)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF4B4B4B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0D0D0)
val onSecondaryContainerLight = Color(0xFF333333)
val tertiaryLight = Color(0xFF555555)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE0E0E0)
val onTertiaryContainerLight = Color(0xFF333333)
val errorLight = Color(0xFFEF4444)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFEE2E2)
val onErrorContainerLight = Color(0xFFB91C1C)
val backgroundLight = Color(0xFFFAFAFA)
val onBackgroundLight = Color(0xFF1A1A1A)
val surfaceLight = Color(0xFFFAFAFA)
val onSurfaceLight = Color(0xFF1A1A1A)
val surfaceVariantLight = Color(0xFFF0F0F0)
val onSurfaceVariantLight = Color(0xFF4B4B4B)
val outlineLight = Color(0xFF808080)
val outlineVariantLight = Color(0xFFD0D0D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF333333)
val inverseOnSurfaceLight = Color(0xFFF5F5F5)
val inversePrimaryLight = Color(0xFFD0D0D0)
val surfaceDimLight = Color(0xFFE0E0E0)
val surfaceBrightLight = Color(0xFFFAFAFA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F5F5)
val surfaceContainerLight = Color(0xFFF0F0F0)
val surfaceContainerHighLight = Color(0xFFE0E0E0)
val surfaceContainerHighestLight = Color(0xFFD0D0D0)

val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFFE0E0E0)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFB0B0B0)
val onSecondaryDark = Color(0xFF333333)
val secondaryContainerDark = Color(0xFF4B4B4B)
val onSecondaryContainerDark = Color(0xFFD0D0D0)
val tertiaryDark = Color(0xFFE0E0E0)
val onTertiaryDark = Color(0xFF262626)
val tertiaryContainerDark = Color(0xFF555555)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFCA5A5)
val onErrorDark = Color(0xFF7F1D1D)
val errorContainerDark = Color(0xFFB91C1C)
val onErrorContainerDark = Color(0xFFFEE2E2)
val backgroundDark = Color(0xFF1A1A1A)
val onBackgroundDark = Color(0xFFE0E0E0)
val surfaceDark = Color(0xFF1A1A1A)
val onSurfaceDark = Color(0xFFE0E0E0)
val surfaceVariantDark = Color(0xFF4B4B4B)
val onSurfaceVariantDark = Color(0xFFD0D0D0)
val outlineDark = Color(0xFF959595)
val outlineVariantDark = Color(0xFF4B4B4B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E0E0)
val inverseOnSurfaceDark = Color(0xFF333333)
val inversePrimaryDark = Color(0xFF000000)
val surfaceDimDark = Color(0xFF1A1A1A)
val surfaceBrightDark = Color(0xFF333333)
val surfaceContainerLowestDark = Color(0xFF0F0F0F)
val surfaceContainerLowDark = Color(0xFF1A1A1A)
val surfaceContainerDark = Color(0xFF262626)
val surfaceContainerHighDark = Color(0xFF333333)
val surfaceContainerHighestDark = Color(0xFF4B4B4B)



